name: Build and Push Docker Image with Scan

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: kvnikhill/github-action

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set build number
      id: vars
      run: echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ env.BUILD_NUMBER }} .

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ env.BUILD_NUMBER }}