name: Deploy to GitOps Repo 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4


    - name: Checkout GitOps repo
      uses: actions/checkout@v4
      with:
        repository: kvnikhildev/CICD3-Githubaction
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: gitops

    - name: Update image tag
      run: |
        cd Deployment
        cp Deployment.templete.yml Deployment.yml
        sed -i "s|image: .*$|image: $github-action:${{ env.BUILD_TAG }}|" Deployment.yml 
        git config user.name "kvnikhilldev"
        git config user.email "kvnikhill@gmail.com"
        git commit -am "Update image tag to $github-action :${{ env.BUILD_TAG }}"
        git push origin main